### ISSUE TITLE
Failed to load the pepper-autocomplete package

### ISSUE THREAD

**Issue by artur-cmc** [TonkWorks/pepper-autocomplete-atom-package#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.17.8-200.fc20.x86_64
**Thrown From**: [pepper-autocomplete](https://github.com/TonkWorks/pepper-autocomplete-atom-package) package, v0.3.0
### Stack Trace

Failed to load the pepper-autocomplete package

```
At Cannot set property 'pepper_ignore_changes' of undefined

TypeError: Cannot set property 'pepper_ignore_changes' of undefined
    at /home/artur/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete-view.coffee:32:36
    at Object.<anonymous> (/home/artur/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete-view.coffee:308:5)
    at Object.<anonymous> (/home/artur/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete-view.coffee:310:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/artur/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete.coffee:8:21)
```
### Commands

```
     -1:57.4 core:confirm (atom-text-editor.editor.mini)
     -0:58.0 core:backspace (atom-text-editor.editor.mini)
     -0:57.1 core:confirm (atom-text-editor.editor.mini)
     -0:45.7 core:backspace (atom-text-editor.editor.mini)
     -0:42.8 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
pepper-autocomplete, v0.3.0
vim-mode, v0.38.0

# Dev
No dev packages
```

**Comment by TonkWorks** [comment]
Looks like results webpage failed to load (and it couldn't set that pepper_ignore_changes flag).  
I'll put a check in place in the release to make sure that "pepper_ignore_changes" exists before trying to set it.   Thanks for the report!

**Comment by TonkWorks** [comment]
I believe this is fixed. Please repoen if you still have issues.
