### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contentWindow' of null

### ISSUE THREAD

**Issue by grunsab** [TonkWorks/pepper-autocomplete-atom-package#3]
Tried autocomplete with Ctrl+1 on a python code base

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.1
**Thrown From**: [pepper-autocomplete](https://github.com/TonkWorks/pepper-autocomplete-atom-package) package, v0.5.0
### Stack Trace

Uncaught TypeError: Cannot read property 'contentWindow' of null

```
At /Users/rishi/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete-view.coffee:30

TypeError: Cannot read property 'contentWindow' of null
  at Function.module.exports.PepperHtmlPreviewView.complete (/Users/rishi/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete-view.coffee:30:66)
  at atom-workspace.<anonymous> (/Users/rishi/.atom/packages/pepper-autocomplete/lib/pepper-autocomplete-view.coffee:11:80)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -3:32.8 core:move-up (atom-text-editor.editor.is-focused)
     -3:31.7 core:move-down (atom-text-editor.editor.is-focused)
     -3:30.8 core:move-up (atom-text-editor.editor.is-focused)
  4x -3:26.6 core:move-left (atom-text-editor.editor.is-focused)
  6x -3:25.2 core:move-down (atom-text-editor.editor.is-focused)
     -1:30.6 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:58.7 core:move-down (atom-text-editor.editor.is-focused)
     -0:52.3 core:move-up (atom-text-editor.editor.is-focused)
     -0:51.9 core:move-down (atom-text-editor.editor.is-focused)
     -0:51.4 core:move-up (atom-text-editor.editor.is-focused)
     -0:49.8 core:move-down (atom-text-editor.editor.is-focused)
  5x -0:45.4 core:move-right (atom-text-editor.editor.is-focused)
  5x -0:09.8 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:04.6 pepper-autocomplete:toggle (atom-text-editor.editor.is-focused)
     -0:02.1 pepper-autocomplete-view:complete (atom-text-editor.editor.is-focused)
     -0:00.5 core:move-left (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "pepper-autocomplete": {
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
pepper-autocomplete, v0.5.0

# Dev
No dev packages
```

**Comment by TonkWorks** [comment]
I'll test it on OS X tomorrow to make sure it works.  Thanks for the report!
